### PR TITLE
Implement spellchecking

### LINKED ISSUE #90: Feature request: Spellcheck
Title says it all. Builtin spellcheck so you don't make typo's...

### PR DESCRIPTION
**Pull request by ghost**
This PR implements spellchecking from libspelling into the commit editor, as filed in #90

I'm relatively new with GJS/GTK, but i mainly followed what was on https://github.com/sonnyp/Commit/issues/90#issuecomment-1636080510 and integrated it following [libspelling's documentation](https://gitlab.gnome.org/chergert/libspelling/-/tree/main#in-javascript). It works but the code might not be perfect :smile: 

---

Closes #90

### CODE REVIEW

**Comment by EncryptedEasty** [comment]
Thanks! Added myself with commit 8ff9544.

**Comment by maxbhardy** [comment]
Hi,

My computer is set up in french, but I usually write my commit messages in english. Since the new version, my whole commit messages are underlined in red since the spell checking is in french (just like my OS). Is it possible to change the language of the spell check, or to deactivate it ?

Thank you!

**Comment by EncryptedEasty** [comment]
@maxbhardy 

Author of the PR here,
Assuming you have English installed (that's up to you how to add it via your distro), available spellcheck languages should show up in the context menu in "Languages", from there you can select which language the spellchecker will use.
 
Commit Screenshot

(In my case it's English and Italian, but it's goining to be different for you).
In any case, you can deactivate the spellchecker by unchecking "Check Spelling" in the same context menu

**Comment by maxbhardy** [comment]
Thank you, I just found this context menu. It would be nice however to be able to set the spell check parameters in the global options.

**Pull request merged**
